version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - graph
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  
  app:
    build: app
    restart: always
    volumes:
      - ./app/src:/src
    secrets:
      - db-password
    ports:
      - 5000:5000
      - 5678:5678
    networks:
      - graph
      - frontnet

  web:
    build: web
    restart: always
    ports:
      - 80:80
    networks:
      - frontnet
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  graph:
    external: true
  frontnet:
